example:
  property: "I AM IN THE DEFAULT"
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-cloud-test?characterEncoding=UTF-8
    username: root
    password: 5456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update